### Numpy array operations

In [1]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])



Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8
Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


### Sorting 

In [3]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


### Filtering without mask and with mask 

In [4]:
print (f"filtering without mask ")
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

print (f"\nfiltering with mask ")
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

filtering without mask 
Even numbers [ 2  4  6  8 10]

filtering with mask 
Numbers greater than 5  [ 6  7  8  9 10]


### Fancy indexing vs np.where ()

In [5]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array)

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### adding and removing 

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

print (f"now deleting from an array ")
deleted_arr = np.delete (combined , [0,2,4])
print (f"the {combined} array after the deletion : {deleted_arr}")

[1 2 3 4 5 6]
now deleting from an array 
the [1 2 3 4 5 6] array after the deletion : [2 4 6]


### array compatibility 

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape) # returned false 
print("Compatibility shapes", a.shape == c.shape) # returned true 


Compatibility shapes False
Compatibility shapes True


### adding of the row and column 

In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))   # use to add new row 
print(f"original shape : {original}")
print(f"with the addition of new row : {with_new_row}")

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))  # use to add new column 
print("With new column\n", with_new_col)

original shape : [[1 2]
 [3 4]]
with the addition of new row : [[1 2]
 [3 4]
 [5 6]]
With new column
 [[1 2 7]
 [3 4 8]]


: 