# Phase 1 

In [1]:
import numpy as np

### ceating an array 

In [2]:

arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2d)

1D array:  [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


### Creating array from scratch 

In [7]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)

array = np.arange (1,13).reshape(3,4)
print (f"array making from the aranage and reshape function : \n{array}")

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.14666249 0.00495965 0.13289063]
 [0.50383984 0.41244044 0.77164539]]
sequnce array: 
 [ 0  2  4  6  8 10]
array making from the aranage and reshape function : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### vector  , matrix and tensor 

In [8]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties 

In [9]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array reshaping 

In [ ]:
arr = np.arange(12)
arr2 = np.arange (1,7).reshape (2,3)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)
print (f"the actual array (arr2)  before the ravel function: \n{arr2}")
view_array = arr2.ravel ()
print (f"\nnow applying the ravel function : \n{view_array}")
view_array [2]= 100
print (f"again printing the actual functin :\n{arr2}")


# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
the actual array (arr2)  before the ravel function: 
[[1 2 3]
 [4 5 6]]

now applying the ravel function : 
[1 2 3 4 5 6]
again printing the actual functin :
[[  1   2 100]
 [  4   5   6]]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


: 